# Generated by Django 3.0.7 on 2020-07-21 05:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Board',
            new_name='Post',
        ),
    ]
